### ISSUE TITLE
Poor Style: Variable Never Used

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [IBM/keyprotect-java-client#1]
https://github.com/IBM/keyprotect-java-client/blob/7f666a990510deef319aacb98a5129ddd4e9fd30/modules/ibm-key-protect-api/src/test/java/com/ibm/cloud/ibm_key_protect_api/v2/model/KeyVersionTest.java#L37

This variable is never used.

**Comment by mrodden** [comment]
Ok Mr Robot
